export const CONNECTORS = [
  {
    id: 'google',
    name: 'Google Workspace',
    shortName: 'Google',
    description: 'Sync users, groups, calendar events, and Drive activity into Sentrix for identity and access risk tracking.',
    category: 'Identity & Productivity',
    logoColor: '#4285F4',
    logoText: 'G',
    oauthUrl: `https://accounts.google.com/o/oauth2/v2/auth`,
    oauthParams: {
      client_id: import.meta.env.VITE_GOOGLE_CLIENT_ID,
      redirect_uri: import.meta.env.VITE_OAUTH_REDIRECT_URI,
      response_type: 'code',
      scope: 'openid email profile https://www.googleapis.com/auth/admin.directory.user.readonly https://www.googleapis.com/auth/calendar.readonly',
      access_type: 'offline',
      prompt: 'consent',
    },
    permissions: ['Read users & groups from Admin Directory', 'Access Google Calendar events', 'Monitor Google Drive file activity', 'Read workspace member profiles'],
  },
  {
    id: 'entra',
    name: 'Microsoft Entra ID',
    shortName: 'Entra ID',
    description: 'Connect Azure AD identities, roles, sign-in logs, and conditional access policies for risk tracking.',
    category: 'Identity & Productivity',
    logoColor: '#0078D4',
    logoText: 'M',
    oauthUrl: `https://login.microsoftonline.com/common/oauth2/v2.0/authorize`,
    tokenUrl: `https://login.microsoftonline.com/common/oauth2/v2.0/token`,
    usePKCE: true,
    oauthParams: {
      client_id: import.meta.env.VITE_MICROSOFT_CLIENT_ID,
      redirect_uri: import.meta.env.VITE_OAUTH_REDIRECT_URI,
      response_type: 'code',
      scope: 'openid email profile offline_access User.Read',
      prompt: 'consent',
    },
    permissions: ['Read directory users and groups', 'Access role and policy assignments', 'Monitor sign-in and audit logs', 'Read conditional access policies'],
  },
  {
    id: 'm365',
    name: 'Microsoft 365 Security',
    shortName: 'M365',
    description: 'Detect email forwarding rules, SharePoint external sharing, guest access risks, and data exposure across Exchange and SharePoint. Maps to SDAIA PDPL and NCA ECC 2-5.',
    category: 'Identity & Productivity',
    logoColor: '#0078D4',
    logoText: 'M',
    // M365 uses the same Entra OAuth — no separate OAuth flow needed.
    // It piggybacks on the existing Entra connector token.
    piggybakcsOn: 'entra',
    permissions: ['Detect email forwarding to external addresses', 'Find SharePoint sites with external sharing', 'Flag stale guest accounts', 'Map findings to SDAIA PDPL & NCA ECC 2-5'],
  },
  {
    id: 'defender',
    name: 'Microsoft Defender',
    shortName: 'Defender',
    description: 'Surface active security alerts, posture gaps, and Secure Score control failures from Microsoft Defender for Cloud and Microsoft Sentinel. Maps to NCA ECC Domain 3 and Domain 4.',
    category: 'Identity & Productivity',
    logoColor: '#00B4D8',
    logoText: 'D',
    piggybakcsOn: 'entra',
    permissions: [
      'Read active security alerts from Defender for Cloud',
      'Pull Microsoft Secure Score and control gaps',
      'Map findings to NCA ECC 3-3 and 3-4',
      'Surface identity and endpoint threat alerts',
    ],
  },
  {
    id: 'sharepoint',
    name: 'SharePoint Security',
    shortName: 'SharePoint',
    description: 'Deep-scan SharePoint sites for external sharing, publicly accessible files, and guest access risks. Maps to NCA ECC 2-3, 2-5, and SDAIA PDPL Article 5 and 13.',
    category: 'Identity & Productivity',
    logoColor: '#038387',
    logoText: 'SP',
    piggybakcsOn: 'entra',
    permissions: [
      'Read all SharePoint sites and file permissions',
      'Detect external and anonymous sharing links',
      'Identify guest users with site access',
      'Map findings to PDPL Article 5 and NCA ECC 2-3',
    ],
  },
  {
    id: 'jira',
    name: 'Jira',
    shortName: 'Jira',
    description: 'Pull issues, projects, and sprints to track compliance tasks, control gaps, and security incidents.',
    category: 'Project Management',
    logoColor: '#0052CC',
    logoText: 'J',
    oauthUrl: `https://auth.atlassian.com/authorize`,
    oauthParams: {
      client_id: import.meta.env.VITE_JIRA_CLIENT_ID,
      redirect_uri: import.meta.env.VITE_OAUTH_REDIRECT_URI,
      response_type: 'code',
      scope: 'read:jira-work read:jira-user write:jira-work manage:jira-webhook offline_access',
      audience: 'api.atlassian.com',
      prompt: 'consent',
    },
    permissions: ['Read projects and issues', 'Access sprint and board data', 'Create and update issues', 'Register webhooks for real-time sync'],
  },
  {
    id: 'notion',
    name: 'Notion',
    shortName: 'Notion',
    description: 'Import pages and databases as evidence, policies, procedures, or documentation linked to controls.',
    category: 'Documentation',
    logoColor: '#000000',
    logoText: 'N',
    oauthUrl: `https://api.notion.com/v1/oauth/authorize`,
    oauthParams: {
      client_id: import.meta.env.VITE_NOTION_CLIENT_ID,
      redirect_uri: import.meta.env.VITE_OAUTH_REDIRECT_URI,
      response_type: 'code',
      owner: 'user',
    },
    permissions: ['Read pages and databases', 'Access workspace members', 'Export page content as evidence', 'Search across workspace content'],
  },
  {
    id: 'slack',
    name: 'Slack',
    shortName: 'Slack',
    description: 'Receive Sentrix alerts, risk notifications, and incident updates directly in your Slack channels.',
    category: 'Communication',
    logoColor: '#4A154B',
    logoText: 'S',
    oauthUrl: `https://slack.com/oauth/v2/authorize`,
    oauthParams: {
      client_id: import.meta.env.VITE_SLACK_CLIENT_ID,
      redirect_uri: import.meta.env.VITE_OAUTH_REDIRECT_URI,
      scope: 'channels:read,chat:write,users:read,team:read',
    },
    permissions: ['Send messages to channels', 'Read channel list', 'Access workspace user directory', 'Post notifications and alerts'],
  },
]

export const CONNECTOR_CATEGORIES = ['All', ...new Set(CONNECTORS.map(c => c.category))]

export const NAV_ITEMS = [
  { id: 'dashboard',  label: 'Dashboard',     icon: 'LayoutDashboard', section: 'workspace' },
  { id: 'incidents',  label: 'Incidents',      icon: 'AlertTriangle',   section: 'workspace' },
  { id: 'findings',   label: 'Findings',       icon: 'FileWarning',     section: 'workspace' },
  { id: 'risks',      label: 'Risk Register',  icon: 'ShieldAlert',     section: 'workspace' },
  { id: 'controls',   label: 'Controls',       icon: 'CheckSquare',     section: 'workspace' },
  { id: 'compliance', label: 'Compliance',     icon: 'BookCheck',       section: 'workspace' },
  { id: 'tasks',      label: 'Tasks',          icon: 'CheckSquare2',    section: 'workspace' },
  { id: 'people',     label: 'People',         icon: 'Users',           section: 'workspace' },
  { id: 'audit',      label: 'Audit Log',      icon: 'ScrollText',      section: 'workspace' },
  { id: 'settings',   label: 'Settings',       icon: 'Settings',        section: 'system'    },
]

export const ROLES = [
  { value: 'admin',              label: 'Admin',              desc: 'Full access, manage users & settings' },
  { value: 'compliance_officer', label: 'Compliance Officer', desc: 'Policy & compliance oversight' },
  { value: 'risk_manager',       label: 'Risk Manager',       desc: 'Risk register & control management' },
  { value: 'auditor',            label: 'Auditor',            desc: 'Audit trails & evidence collection' },
  { value: 'viewer',             label: 'Viewer',             desc: 'Read-only access to all modules' },
]

export const INDUSTRIES = [
  'Financial Services', 'Healthcare', 'Technology', 'Manufacturing',
  'Retail', 'Energy & Utilities', 'Government & Public Sector',
  'Legal & Professional Services', 'Education', 'Other',
]

export const COMPANY_SIZES = ['1–50', '51–200', '201–1,000', '1,001–5,000', '5,000+']
