/* ── Report building blocks ───────────────────────────────────────────────────
 *
 * Every RISYS report is built from these, so a board pack, an ECC status
 * report and an audit report share one visual language: the ink cover with the
 * cream mark, DM Serif section titles in wine, crimson rules, blush table heads.
 * -------------------------------------------------------------------------- */
import { Document, Page, Image, StyleSheet } from '@react-pdf/renderer'
import { View, Text } from './rtl'
import { C, BAND } from './theme'
import { FONT_SANS, FONT_DISPLAY, reportAssets, FONT_ARABIC } from './assets'
import { tx } from '@/lib/i18n'

const PAD_X = 42
const PAD_TOP = 64
const PAD_BOTTOM = 56

export const s = StyleSheet.create({
  page:      { fontFamily: [FONT_SANS, FONT_ARABIC], fontSize: 8.6, color: C.text, lineHeight: 1.45,
               paddingTop: PAD_TOP, paddingBottom: PAD_BOTTOM, paddingHorizontal: PAD_X, backgroundColor: C.white },
  p:         { marginBottom: 6 },
  muted:     { color: C.text3 },
  text2:     { color: C.text2 },
  bold:      { fontWeight: 600 },
  eyebrow:   { fontSize: 7, fontWeight: 600, color: C.rose, letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 3 },
  h2:        { fontFamily: FONT_DISPLAY, fontSize: 19, color: C.wine, lineHeight: 1.15 },
  h3:        { fontSize: 10.5, fontWeight: 600, color: C.crimson, marginTop: 12, marginBottom: 5 },
  h4:        { fontSize: 8.6, fontWeight: 600, color: C.rose, marginTop: 8, marginBottom: 3 },
  row:       { flexDirection: 'row' },
})

/* ── Document, cover, content page ────────────────────────────────────────── */

export function ReportDocument({ meta, children }) {
  return (
    <Document title={`${meta.title} — ${meta.orgName}`} author="RISYS" subject={meta.title}
              creator="RISYS" producer="RISYS" keywords={meta.reportId ?? ''}>
      {children}
    </Document>
  )
}

export function CoverPage({ meta }) {
  const { markLight } = reportAssets()
  const rows = [
    ['Prepared for', meta.audience],
    ['Organisation', meta.orgName],
    meta.periodLabel ? ['Reporting period', meta.periodLabel] : null,
    ['Generated', meta.generatedLabel],
    meta.generatedBy ? ['Generated by', meta.generatedBy] : null,
    ['Classification', meta.classification],
    meta.reportId ? ['Report ID', meta.reportId] : null,
  ].filter(Boolean)
  return (
    <Page size="A4" style={{ fontFamily: FONT_SANS, backgroundColor: C.white }}>
      <View style={{ backgroundColor: C.ink, height: '58%', paddingHorizontal: 48, paddingTop: 54, paddingBottom: 40,
                     justifyContent: 'space-between' }}>
        <View style={[s.row, { alignItems: 'center' }]}>
          {markLight ? <Image src={markLight} style={{ width: 30, height: 31, marginHorizontal: 5 }} /> : null}
          <Text style={{ fontSize: 9, fontWeight: 600, color: C.taupe, letterSpacing: 3 }}>{tx('RISYS')}</Text>
        </View>
        <View>
          <Text style={{ fontSize: 8, fontWeight: 600, color: C.taupe, letterSpacing: 1.6, textTransform: 'uppercase', marginBottom: 10 }}>
            {meta.eyebrow}
          </Text>
          <Text style={{ fontFamily: FONT_DISPLAY, fontSize: 36, color: C.cream, lineHeight: 1.08, marginBottom: 14 }}>
            {meta.title}
          </Text>
          <Text style={{ fontSize: 12, color: C.blush }}>{meta.orgName}</Text>
          {meta.periodLabel ? <Text style={{ fontSize: 10, color: C.taupe, marginTop: 3 }}>{meta.periodLabel}</Text> : null}
        </View>
      </View>
      <View style={{ height: 4, backgroundColor: C.crimson }} />
      <View style={{ paddingHorizontal: 48, paddingTop: 30 }}>
        {rows.map(([k, v]) => (
          <View key={k} style={[s.row, { borderBottomWidth: 0.6, borderBottomColor: C.border, paddingVertical: 7 }]}>
            <Text style={{ width: 130, fontSize: 7.5, fontWeight: 600, color: C.rose, letterSpacing: 0.8, textTransform: 'uppercase' }}>{k}</Text>
            <Text style={{ flex: 1, fontSize: 9, color: C.text }}>{v}</Text>
          </View>
        ))}
        <Text style={{ fontSize: 7.2, color: C.text3, marginTop: 18, lineHeight: 1.5 }}>
          {meta.coverNote ??
            tx(
              'Generated from the organisation’s records in RISYS at the time shown. A copy of this file and the data it was built from are archived in RISYS under the Report ID above, with a SHA-256 fingerprint of the file.'
            )}
        </Text>
      </View>
    </Page>
  )
}

export function ContentPage({ meta, children }) {
  const { markDark } = reportAssets()
  // Header and footer are drawn by render functions so react-pdf builds them
  // afresh on every page. As plain `fixed` children they were re-laid-out from
  // the previous page, and the inherited line height compounded page by page
  // (1.45 × font size, then × font size again …) until, around page 15, the
  // numbers overflowed and generation failed with "unsupported number".
  const header = () => (
    <>
      {markDark ? <Image src={markDark} style={{ width: 11, height: 11, marginHorizontal: 3 }} /> : null}
      <Text style={{ fontSize: 7, lineHeight: 1.3, fontWeight: 600, color: C.crimson, letterSpacing: 1.2 }}>RISYS</Text>
      <Text style={{ fontSize: 7, lineHeight: 1.3, color: C.text3, marginLeft: 8, flex: 1 }}>{meta.orgName} · {meta.shortTitle ?? meta.title}</Text>
      {meta.periodLabel ? <Text style={{ fontSize: 7, lineHeight: 1.3, color: C.text3 }}>{meta.periodLabel}</Text> : null}
    </>
  )
  const footer = ({ pageNumber, totalPages }) => (
    <>
      <Text style={{ fontSize: 6.8, lineHeight: 1.3, color: C.text3, flex: 1 }}>{meta.classification}</Text>
      {meta.reportId ? <Text style={{ fontSize: 6.8, lineHeight: 1.3, color: C.text3, marginRight: 14 }}>{tx('Report ID')} {meta.reportId.slice(0, 8)}</Text> : null}
      <Text style={{ fontSize: 6.8, lineHeight: 1.3, color: C.crimson, fontWeight: 600 }}>{`${pageNumber} / ${totalPages}`}</Text>
    </>
  )
  return (
    <Page size="A4" style={s.page} wrap>
      <View fixed render={header}
            style={{ position: 'absolute', top: 24, left: PAD_X, right: PAD_X, flexDirection: 'row',
                     alignItems: 'center', borderBottomWidth: 0.6, borderBottomColor: C.border, paddingBottom: 7 }} />
      {children}
      <View fixed render={footer}
            style={{ position: 'absolute', bottom: 22, left: PAD_X, right: PAD_X, flexDirection: 'row',
                     borderTopWidth: 0.6, borderTopColor: C.border, paddingTop: 6 }} />
    </Page>
  )
}

/* ── Headings and text ───────────────────────────────────────────────────── */

export function SectionTitle({ eyebrow, title, first, breakBefore }) {
  return (
    <View break={breakBefore} minPresenceAhead={90} style={{ marginTop: first ? 0 : 16, marginBottom: 10 }}>
      {eyebrow ? <Text style={s.eyebrow}>{eyebrow}</Text> : null}
      <Text style={s.h2}>{title}</Text>
      <View style={[s.row, { marginTop: 7 }]}>
        <View style={{ width: 34, height: 2, backgroundColor: C.crimson }} />
        <View style={{ flex: 1, height: 0.6, backgroundColor: C.border, marginTop: 0.7 }} />
      </View>
    </View>
  )
}

export const H3 = ({ children }) => <Text minPresenceAhead={40} style={s.h3}>{children}</Text>
export const H4 = ({ children }) => <Text minPresenceAhead={30} style={s.h4}>{children}</Text>
export const P = ({ children, style }) => <Text style={[s.p, style]}>{children}</Text>
export const Muted = ({ children, style }) => <Text style={[s.p, s.muted, { fontSize: 7.4 }, style]}>{children}</Text>
export const B = ({ children }) => <Text style={s.bold}>{children}</Text>

export function Lead({ children }) {
  return <Text style={{ fontSize: 10, color: C.text, lineHeight: 1.5, marginBottom: 10 }}>{children}</Text>
}

export function Bullets({ items, color = C.crimson }) {
  return (
    <View style={{ marginBottom: 6 }}>
      {items.map((it, i) => (
        <View key={i} wrap={false} style={[s.row, { marginBottom: 3 }]}>
          <Text style={{ width: 12, color }}>—</Text>
          <Text style={{ flex: 1 }}>{it}</Text>
        </View>
      ))}
    </View>
  )
}

export function Callout({ title, children, tone = 'crimson' }) {
  const bar = tone === 'crimson' ? C.crimson : tone === 'amber' ? '#92400E' : C.rose
  const bg = tone === 'crimson' ? C.crimsonWash : tone === 'amber' ? '#FFFBEB' : C.surface
  return (
    <View wrap={false} style={{ flexDirection: 'row', backgroundColor: bg, marginVertical: 8 }}>
      <View style={{ width: 3, backgroundColor: bar }} />
      <View style={{ flex: 1, paddingVertical: 8, paddingHorizontal: 10 }}>
        {title ? <Text style={{ fontWeight: 600, color: bar, marginBottom: 3 }}>{title}</Text> : null}
        {typeof children === 'string' ? <Text>{children}</Text> : children}
      </View>
    </View>
  )
}

/* ── Pills, tiles ─────────────────────────────────────────────────────────── */

export function Pill({ meta, label, small }) {
  const m = meta ?? BAND.none
  return (
    <View style={{ alignSelf: 'flex-start', backgroundColor: m.bg, borderWidth: 0.6, borderColor: m.border,
                   borderRadius: 7, paddingHorizontal: small ? 4 : 5.5, paddingVertical: small ? 0.8 : 1.4 }}>
      <Text style={{ fontSize: small ? 6.4 : 7, fontWeight: 600, color: m.color, lineHeight: 1.2 }}>{label ?? m.label}</Text>
    </View>
  )
}

export function KpiRow({ items }) {
  return (
    <View wrap={false} style={[s.row, { marginBottom: 10, marginTop: 2 }]}>
      {items.map((k, i) => (
        <View key={i} style={{ flex: 1, backgroundColor: C.surface, borderTopWidth: 2,
                               borderTopColor: k.tone === 'alert' ? C.crimson : k.tone === 'good' ? '#166534' : C.blush,
                               paddingVertical: 8, paddingHorizontal: 9, marginRight: i === items.length - 1 ? 0 : 6 }}>
          <Text style={{ fontSize: 6.6, fontWeight: 600, color: C.rose, letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 4 }}>
            {k.label}
          </Text>
          <Text style={{ fontFamily: FONT_DISPLAY, fontSize: 21, color: k.tone === 'alert' ? C.crimson : C.ink, lineHeight: 1 }}>
            {k.value}
          </Text>
          {k.sub ? <Text style={{ fontSize: 6.8, color: C.text3, marginTop: 4, lineHeight: 1.3 }}>{k.sub}</Text> : null}
        </View>
      ))}
    </View>
  )
}

/* ── Table ────────────────────────────────────────────────────────────────── */

/**
 * columns: [{ key, label, width (flex weight or number), align, render(row) }]
 * A row never splits across pages. `heading` (optional) is kept on the same
 * page as the column header and the first row.
 */
export function Table({ columns, rows, empty = 'None recorded.', dense, indentKey, heading }) {
  const total = columns.reduce((a, c) => a + (c.width ?? 1), 0)
  const cellStyle = (c) => ({
    width: `${((c.width ?? 1) / total) * 100}%`,
    paddingHorizontal: 5,
    paddingVertical: dense ? 3.2 : 4.6,
    textAlign: c.align ?? 'left',
  })
  const header = (
    <View style={[s.row, { backgroundColor: C.surface, borderTopWidth: 0.6, borderTopColor: C.border,
                           borderBottomWidth: 1.2, borderBottomColor: C.crimson }]}>
      {columns.map((c) => (
        <Text key={c.key} style={[cellStyle(c), { fontSize: 6.6, fontWeight: 600, color: C.crimson,
                                                  letterSpacing: 0.7, textTransform: 'uppercase' }]}>
          {c.label}
        </Text>
      ))}
    </View>
  )
  // Rows may split across a page. Unbreakable rows (wrap={false}) made
  // react-pdf squeeze whole tables into a strip at the foot of some pages.
  const row = (r, i) => (
    <View key={i}
          style={[s.row, { flexShrink: 0, backgroundColor: i % 2 ? C.hover : C.white, borderBottomWidth: 0.6,
                           borderBottomColor: C.border3, alignItems: 'flex-start' }]}>
      {columns.map((c, ci) => {
        const v = c.render ? c.render(r) : r[c.key]
        const indent = ci === 0 && indentKey && r[indentKey] ? 10 : 0
        return (
          <View key={c.key} style={[cellStyle(c), { paddingLeft: 5 + indent,
                                                     alignItems: c.align === 'right' ? 'flex-end' : c.align === 'center' ? 'center' : 'flex-start' }]}>
            {v === null || v === undefined || v === ''
              ? <Text style={{ fontSize: dense ? 7.4 : 7.8, color: C.text3 }}>—</Text>
              : (typeof v === 'string' || typeof v === 'number')
                ? <Text style={{ fontSize: dense ? 7.4 : 7.8, color: ci === 0 ? C.text : C.text2,
                                 fontWeight: c.bold ? 600 : 400, textAlign: c.align ?? 'left' }}>{String(v)}</Text>
                : v}
          </View>
        )
      })}
    </View>
  )
  // The headings and the column header carry minPresenceAhead, so they move to
  // the next page rather than sit alone at its foot. (This used to be one wrap={false} group holding the heading,
  // header and first row; react-pdf then squeezed whole tables into a strip
  // at the bottom of the page when that group had to move.)
  return (
    <View style={{ marginBottom: 10 }}>
      {heading}
      <View minPresenceAhead={30}>{header}</View>
      {rows.length === 0 ? (
        <Text style={{ paddingVertical: 8, paddingHorizontal: 5, color: C.text3, borderBottomWidth: 0.6, borderBottomColor: C.border }}>
          {empty}
        </Text>
      ) : rows.map((r, i) => row(r, i))}
    </View>
  )
}

/* ── Charts ───────────────────────────────────────────────────────────────── */

/**
 * Likelihood × impact heat map. cells: { 'l-i': { band, count } }.
 * Likelihood runs 5 → 1 top to bottom, impact 1 → 5 left to right — the
 * orientation the register uses on screen.
 */
export function HeatMap({ title, cells, dims = 5, total, cellSize = 27 }) {
  const rowsL = Array.from({ length: dims }, (_, k) => dims - k)
  const colsI = Array.from({ length: dims }, (_, k) => k + 1)
  return (
    <View wrap={false} style={{ alignItems: 'flex-start' }}>
      <Text style={{ fontSize: 8, fontWeight: 600, color: C.crimson, marginBottom: 5 }}>
        {title}{typeof total === 'number' ? <Text style={{ color: C.text3, fontWeight: 400 }}> · {total} {tx('scored')}</Text> : null}
      </Text>
      <View style={s.row}>
        <View style={{ width: 12, justifyContent: 'center' }}>
          <Text style={{ fontSize: 6, color: C.text3, transform: 'rotate(-90deg)', width: 60, marginLeft: -24 }}>{tx('LIKELIHOOD')}</Text>
        </View>
        <View>
          {rowsL.map((l) => (
            <View key={l} style={s.row}>
              <Text style={{ width: 10, fontSize: 6.2, color: C.text3, textAlign: 'right', paddingRight: 3, paddingTop: cellSize / 2 - 4 }}>{l}</Text>
              {colsI.map((i) => {
                const cell = cells[`${l}-${i}`] ?? {}
                const m = BAND[cell.band] ?? BAND.none
                const n = cell.count ?? 0
                return (
                  <View key={i} style={{ width: cellSize, height: cellSize, margin: 1, backgroundColor: n ? m.color : m.bg,
                                         borderWidth: 0.6, borderColor: m.border, alignItems: 'center', justifyContent: 'center' }}>
                    {n ? <Text style={{ fontSize: 8.5, fontWeight: 700, color: C.white }}>{n}</Text> : null}
                  </View>
                )
              })}
            </View>
          ))}
          <View style={[s.row, { marginLeft: 10 }]}>
            {colsI.map((i) => (
              <Text key={i} style={{ width: cellSize, margin: 1, fontSize: 6.2, color: C.text3, textAlign: 'center' }}>{i}</Text>
            ))}
          </View>
          <Text style={{ fontSize: 6, color: C.text3, textAlign: 'center', marginLeft: 10 }}>{tx('IMPACT')}</Text>
        </View>
      </View>
    </View>
  )
}

export function BandLegend() {
  return (
    <View style={[s.row, { marginTop: 4, flexWrap: 'wrap' }]}>
      {['critical', 'high', 'medium', 'low'].map((b) => (
        <View key={b} style={[s.row, { alignItems: 'center', marginRight: 10 }]}>
          <View style={{ width: 7, height: 7, backgroundColor: BAND[b].color, marginRight: 3 }} />
          <Text style={{ fontSize: 6.6, color: C.text2 }}>{BAND[b].label}</Text>
        </View>
      ))}
    </View>
  )
}

/**
 * One horizontal bar split into segments. segments: [{ value, meta }].
 * Empty remainder is shown as an outlined track so "not assessed" is visible
 * rather than simply shorter.
 */
export function StackedBar({ segments, total, height = 9 }) {
  const sum = total ?? segments.reduce((a, x) => a + x.value, 0)
  return (
    <View style={[s.row, { height, backgroundColor: C.white, borderWidth: 0.6, borderColor: C.border }]}>
      {sum > 0 && segments.filter((x) => x.value > 0).map((x, i) => (
        <View key={i} style={{ width: `${(x.value / sum) * 100}%`, backgroundColor: x.meta.color }} />
      ))}
    </View>
  )
}

export function Legend({ items }) {
  return (
    <View style={[s.row, { flexWrap: 'wrap', marginTop: 3, marginBottom: 6 }]}>
      {items.map((m, i) => (
        <View key={i} style={[s.row, { alignItems: 'center', marginRight: 10, marginBottom: 2 }]}>
          <View style={{ width: 7, height: 7, backgroundColor: m.color, marginRight: 3 }} />
          <Text style={{ fontSize: 6.6, color: C.text2 }}>{m.label}</Text>
        </View>
      ))}
    </View>
  )
}

/** A two-column label / value block, for engagement and report details. */
export function FactGrid({ facts }) {
  return (
    <View style={{ marginBottom: 10 }}>
      {facts.filter(Boolean).map(([k, v], i) => (
        <View key={i} wrap={false} style={[s.row, { borderBottomWidth: 0.6, borderBottomColor: C.border3, paddingVertical: 4 }]}>
          <Text style={{ width: 120, fontSize: 7, fontWeight: 600, color: C.rose, letterSpacing: 0.6, textTransform: 'uppercase', paddingTop: 1 }}>{k}</Text>
          {typeof v === 'string' || typeof v === 'number' || v == null
            ? <Text style={{ flex: 1 }}>{v ?? '—'}</Text>
            : <View style={{ flex: 1 }}>{v}</View>}
        </View>
      ))}
    </View>
  )
}
