import { useNavigate } from 'react-router-dom'
import { FileText, Landmark, ShieldCheck, ClipboardCheck } from 'lucide-react'
import { Topbar } from '@/components/layout/Topbar'
import { useAuth } from '@/hooks/useAuth'
import { usePermissions } from '@/hooks/usePermissions'
import { useReports } from '@/hooks/useReports'
import { useAudits } from '@/hooks/useAudits'
import { REPORT_TYPES } from '@/lib/reports/theme'
import { ReportArchive } from './ReportArchive'
import { tx } from '@/lib/i18n'

/* ── Reports ──────────────────────────────────────────────────────────────────
 *
 * Board and regulator reporting. Each report is a PDF generated from the
 * organisation's records at that moment, filed in an archive that cannot be
 * edited or deleted, with the data it was built from and a SHA-256 of the
 * file — so "what did the board see in March?" always has an answer.
 * -------------------------------------------------------------------------- */

const CARDS = [
  { type: 'board_pack', icon: Landmark, blurb: tx(
    'Quarterly pack for the board or risk committee — what needs attention, risk before and after controls, accepted risks, ECC position, incidents and audit.'
  ) },
  { type: 'ecc_status', icon: ShieldCheck, blurb: tx(
    'Requirement-by-requirement NCA ECC-2:2024 status with measurements, controls, evidence and gaps — for a regulator, assessor or management.'
  ) },
  { type: 'audit_report', icon: ClipboardCheck, blurb: tx(
    'The formal report of an audit engagement — opinion, findings with management responses, and the testing behind them.'
  ) },
]

export function ReportsPage() {
  const { organization } = useAuth()
  const perms = usePermissions()
  const navigate = useNavigate()
  const { runs, loading } = useReports()
  const { engagements } = useAudits()

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <Topbar title={tx('Reports')} subtitle={organization?.name}
        actions={perms.canGenerateReports && (
          <button className="btn-primary" onClick={() => navigate('/app/reports/new')}><FileText size={14} /> {tx('Generate report')}</button>
        )} />

      <div className="page-content" style={{ flex: 1, overflowY: 'auto' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: 12, marginBottom: 16 }}>
          {CARDS.map(({ type, icon: Icon, blurb }) => (
            <div key={type} className="section" style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 8 }}>
              <div className="flex items-center" style={{ gap: 8 }}>
                <Icon size={16} style={{ color: 'var(--crimson)' }} />
                <span style={{ fontSize: 'var(--t-section)', fontWeight: 600, color: 'var(--text)' }}>{REPORT_TYPES[type].label}</span>
              </div>
              <p style={{ fontSize: 'var(--t-sm)', color: 'var(--text-3)', margin: 0, lineHeight: 1.55, flex: 1 }}>{blurb}</p>
              <div style={{ fontSize: 'var(--t-meta)', color: 'var(--text-3)' }}>{tx('For:')} {REPORT_TYPES[type].audience}</div>
              {perms.canGenerateReports && (
                <div><button className="btn-secondary" onClick={() => navigate(`/app/reports/new?type=${type}`)}
                  disabled={type === 'audit_report' && !engagements.length}
                  title={type === 'audit_report' && !engagements.length ? tx('Create an audit engagement first') : undefined}>{tx('Generate')}</button></div>
              )}
            </div>
          ))}
        </div>

        <section className="section">
          <div style={{ padding: '11px 16px', borderBottom: '1px solid var(--border)' }}>
            <h3 style={{ fontSize: 'var(--t-section)', fontWeight: 600, margin: 0 }}>{tx('Archive')}</h3>
            <p style={{ fontSize: 'var(--t-meta)', color: 'var(--text-3)', margin: '3px 0 0' }}>{tx(
              'Every report ever generated, as it was generated. Reports cannot be edited or deleted; use Verify to confirm a file is unchanged.'
            )}</p>
          </div>
          <ReportArchive runs={runs} loading={loading} canRecord={perms.canGenerateReports}
            emptyText={perms.canGenerateReports ? tx('Generate a board pack or an ECC status report to start the archive.') : tx(
              'Reports generated by your risk, compliance or audit team will appear here.'
            )} />
        </section>
      </div>

    </div>
  )
}
