-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table public.audit_engagements       enable row level security;
alter table public.audit_scope_items       enable row level security;
alter table public.audit_evidence_requests enable row level security;
alter table public.audit_evidence_files    enable row level security;
alter table public.audit_findings          enable row level security;
alter table public.report_runs             enable row level security;

-- Suspension guard, same as every tenant table.
do $$
declare t text;
begin
  foreach t in array array['audit_engagements','audit_scope_items','audit_evidence_requests',
                           'audit_evidence_files','audit_findings','report_runs'] loop
    execute format('create policy tenant_active_guard on public.%I as restrictive for all to authenticated
                      using (org_id is null or is_org_active(org_id))
                      with check (org_id is null or is_org_active(org_id))', t);
    -- Everyone in the organisation reads audit and report records.
    execute format('create policy %I on public.%I for select to authenticated using (is_org_member(org_id))',
                   t || '_select', t);
  end loop;
end $$;

-- Engagements and scope: audit writers only.
create policy audit_engagements_write on public.audit_engagements for insert to authenticated
  with check (is_audit_writer(org_id));
create policy audit_engagements_update on public.audit_engagements for update to authenticated
  using (is_audit_writer(org_id)) with check (is_audit_writer(org_id));
create policy audit_engagements_delete on public.audit_engagements for delete to authenticated
  using (is_org_admin(org_id) and status in ('planned','cancelled'));

create policy audit_scope_items_insert on public.audit_scope_items for insert to authenticated
  with check (is_audit_writer(org_id));
create policy audit_scope_items_update on public.audit_scope_items for update to authenticated
  using (is_audit_writer(org_id)) with check (is_audit_writer(org_id));
create policy audit_scope_items_delete on public.audit_scope_items for delete to authenticated
  using (is_audit_writer(org_id));

-- Evidence requests: auditors raise and review them; the person asked
-- answers them. The trigger below limits what the answerer may change.
create policy audit_evidence_requests_insert on public.audit_evidence_requests for insert to authenticated
  with check (is_audit_writer(org_id));
create policy audit_evidence_requests_update on public.audit_evidence_requests for update to authenticated
  using (is_audit_writer(org_id) or (requested_from = auth.uid() and my_role(org_id) <> 'viewer'))
  with check (is_audit_writer(org_id) or (requested_from = auth.uid() and my_role(org_id) <> 'viewer'));
create policy audit_evidence_requests_delete on public.audit_evidence_requests for delete to authenticated
  using (is_audit_writer(org_id) and status = 'open');

-- Evidence files: auditors attach workpapers; the person asked attaches their
-- answer. Nobody deletes a file once its request has been accepted.
create policy audit_evidence_files_insert on public.audit_evidence_files for insert to authenticated
  with check (
    is_audit_writer(org_id)
    or (request_id is not null and my_role(org_id) <> 'viewer' and exists (
          select 1 from public.audit_evidence_requests r
           where r.id = request_id and r.requested_from = auth.uid() and r.status in ('open','rejected')))
  );
create policy audit_evidence_files_delete on public.audit_evidence_files for delete to authenticated
  using (
    (is_audit_writer(org_id) or uploaded_by = auth.uid())
    and not exists (select 1 from public.audit_evidence_requests r where r.id = request_id and r.status = 'accepted')
  );

-- Findings: auditors write them; the response owner writes the management
-- response and moves remediation along. The trigger limits the owner's edits.
create policy audit_findings_insert on public.audit_findings for insert to authenticated
  with check (is_audit_writer(org_id));
create policy audit_findings_update on public.audit_findings for update to authenticated
  using (is_audit_writer(org_id) or (response_owner = auth.uid() and my_role(org_id) <> 'viewer'))
  with check (is_audit_writer(org_id) or (response_owner = auth.uid() and my_role(org_id) <> 'viewer'));
create policy audit_findings_delete on public.audit_findings for delete to authenticated
  using (is_audit_writer(org_id) and status = 'draft');

-- Reports: generated by the reporting roles; never deleted.
create policy report_runs_insert on public.report_runs for insert to authenticated
  with check (can_generate_reports(org_id) and generated_by = auth.uid());
create policy report_runs_update on public.report_runs for update to authenticated
  using (can_generate_reports(org_id)) with check (can_generate_reports(org_id));;
